### ISSUE TITLE
Manifest version 2 breaks the authentication

### ISSUE THREAD

**Issue by marmarko** [alexsukhodolsky/doorkeeper-chrome-extension#1]
It seems that version 2 of Chrome extension manifest is creating issues. When I authorize the authentication, the final screen shows and never closes. The same code works without any issues when I change the manifest version to 1.

**Comment by marmarko** [comment]
The solution is to move 

<script>
  var url = unescape(window.location.href.match(/from=([^&]+)/)[1]);
  var adapterName = OAuth2.lookupAdapterName(url.substring(0, url.indexOf('?')));
  var finisher = new OAuth2(adapterName, OAuth2.FINISH);
</script>


into a .js file and then include that file in oauth2.html

**Comment by alexsukhodolsky** [comment]
Thanks for the feedback and the code sample.

I just synced the latest changes from https://github.com/borismus/oauth2-extensions.git and added the manifest 2 changes.
